title: The Data Sleuth
description: An exploratory blog created to help me improve my Data Science skills
author: Jess Chace
github: https://github.com/thedatasleuth
about: Investigator | Data Scientist
disqus_shortname: jesster413-github-io
google_analytics: UA-122624159-1
avatar_url: /static/img/female-sleuth-type-3_1f575-1f3fc-200d-2640-fe0f.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/jessica-chace/"

    - icon: fa-github
      link: "https://github.com/thedatasleuth"

    - icon: fa-briefcase
      link: "https://resume.github.io/?thedatasleuth"

    - icon: fa-envelope
      link: "mailto:chace.jessica@gmail.com"

share:
  twitter_username:
  fb_appid:

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Resources
      url: /resources/
    - text: Events
      url: /events/
    - text: Contact
      url: /contact/
    - text: XML Feed
      url: /feed.xml


url: "https://thedatasleuth.github.io"
baseurl: ""
paginate: 0
per_page: 4
paginate_path: "/page/:num/"
markdown: kramdown
kramdown:
    math_engine: mathjax
gems:
  - jekyll-paginate
  - jekyll-gist
  # - jekyll-time-to-read
plugins:
  - jekyll-time-to-read

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
